version: "3.9"

services:
  db:
    image: postgres:12
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: rustapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rustapicrud_default

  rustapp:
    container_name: rustapp
    image: francescoxx/rustapp:1.0.0
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres123@db:5432/rustapp
    depends_on:
      - db
    networks:
      - rustapicrud_default

  reactbe:
    container_name: reactbe
    image: node:24-alpine
    networks:
      - rustapicrud_default

volumes:
  db_data:

networks:
  rustapicrud_default:
    external: true
