version: '3.9'

services:
  rustapp:
    container_name: rustapp
    image: francescoxx/rustapp:1.0.0
    networks:
      - rustapicrud_default

  db:
    container_name: db
    image: 'postgres:12'
    networks:
      - rustapicrud_default

  reactbe:
    container_name: reactbe
    image: node:24-alpine
    networks:
      - rustapicrud_default

networks:
  rustapicrud_default:
    external: true
