version: '3.9'

services:
  rustapp:
    container_name: rustapp
    image: francescoxx/rustapp:1.0.0
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres123@db:5432/rustapp
    networks:
      - rustapicrud_default

  db:
    image: postgres:12
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: rustapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rustapicrud_default

  reactbe:
    container_name: reactbe
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./reactbe:/app
    command: ["npm", "start"]
    ports:
      - "5173:5173"
    networks:
      - rustapicrud_default

volumes:
  db_data:

networks:
  rustapicrud_default:
    external: true
